name: CI

permissions:
    contents: write

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Fetch Binaries
        run: sh fetch.sh

      - name: Create ZIP Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          directory: /tmp/bins/
          type: 'zip'
          filename: 'release.zip'

      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}